package com.medianest.util

import android.util.Log
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

data class LogEntry(
    val timestamp: String,
    val dateGroup: String,
    val tag: String,
    val message: String,
    val level: LogLevel
)

enum class LogLevel { DEBUG, INFO, WARN, ERROR }

object Logger {
    private val _logs = MutableStateFlow<List<LogEntry>>(emptyList())
    val logs: StateFlow<List<LogEntry>> = _logs.asStateFlow()

    private val dateFormat = SimpleDateFormat("HH:mm:ss.SSS", Locale.getDefault())
    private val groupDateFormat = SimpleDateFormat("dd-MMM-yyyy", Locale.US)
    private const val MAX_LOGS = 500

    private fun addLog(tag: String, msg: String, level: LogLevel) {
        val now = Date()
        val entry = LogEntry(
            timestamp = dateFormat.format(now),
            dateGroup = groupDateFormat.format(now).uppercase(Locale.US),
            tag = tag,
            message = msg,
            level = level
        )
        val currentList = _logs.value.toMutableList()
        currentList.add(0, entry) // Newest first
        if (currentList.size > MAX_LOGS) {
            currentList.removeAt(currentList.size - 1)
        }
        _logs.value = currentList
    }

    fun v(tag: String, msg: String, throwable: Throwable? = null) {
        Log.v("MediaNest_$tag", msg, throwable)
        addLog(tag, "$msg ${throwable?.message ?: ""}", LogLevel.DEBUG)
    }

    fun d(tag: String, msg: String, throwable: Throwable? = null) {
        Log.d("MediaNest_$tag", msg, throwable)
        addLog(tag, "$msg ${throwable?.message ?: ""}", LogLevel.DEBUG)
    }

    fun i(tag: String, msg: String, throwable: Throwable? = null) {
        Log.i("MediaNest_$tag", msg, throwable)
        addLog(tag, "$msg ${throwable?.message ?: ""}", LogLevel.INFO)
    }

    fun w(tag: String, msg: String, throwable: Throwable? = null) {
        Log.w("MediaNest_$tag", msg, throwable)
        addLog(tag, "$msg ${throwable?.message ?: ""}", LogLevel.WARN)
    }

    fun e(tag: String, msg: String, throwable: Throwable? = null) {
        Log.e("MediaNest_$tag", msg, throwable)
        addLog(tag, "$msg ${throwable?.message ?: ""}", LogLevel.ERROR)
    }

    fun clear() {
        _logs.value = emptyList()
    }

    /**
     * Reads system logcat logs generated by this process (including C++ native FFmpeg logs,
     * Media3, Oboe, system frameworks, and android.util.Log calls).
     */
    fun getProcessLogcatLogs(
        filterTagOrKeyword: String = "",
        minLevel: LogLevel? = null
    ): List<String> {
        return try {
            val pid = android.os.Process.myPid()
            val process = Runtime.getRuntime().exec(arrayOf("logcat", "-d", "-v", "threadtime", "--pid", pid.toString()))
            val reader = java.io.BufferedReader(java.io.InputStreamReader(process.inputStream))
            val lines = mutableListOf<String>()
            val filterLC = filterTagOrKeyword.trim().lowercase(Locale.getDefault())

            var line = reader.readLine()
            while (line != null) {
                if (line.isNotBlank()) {
                    var keep = true
                    if (filterLC.isNotEmpty()) {
                        keep = line.lowercase(Locale.getDefault()).contains(filterLC)
                    }
                    if (keep && minLevel != null) {
                        val levelChar = when (minLevel) {
                            LogLevel.ERROR -> " E "
                            LogLevel.WARN -> " W "
                            LogLevel.INFO -> " I "
                            LogLevel.DEBUG -> " D "
                        }
                        keep = line.contains(levelChar) || line.contains(" E/") || line.contains(" W/") || line.contains(" I/") || line.contains(" D/")
                    }
                    if (keep) {
                        lines.add(line)
                    }
                }
                line = reader.readLine()
            }
            reader.close()
            process.destroy()
            lines.reversed() // Newest first
        } catch (e: Exception) {
            listOf("Failed to retrieve ADB logcat: ${e.message}")
        }
    }

    /**
     * Clears the system logcat buffer for this app session.
     */
    fun clearLogcatBuffer() {
        try {
            Runtime.getRuntime().exec(arrayOf("logcat", "-c")).waitFor()
        } catch (e: Exception) {
            Log.e("Logger", "Failed to clear logcat buffer", e)
        }
    }

    /**
     * Installs a global uncaught exception handler to capture app crashes in our internal logs.
     */
    fun installCrashHandler() {
        val defaultHandler = Thread.getDefaultUncaughtExceptionHandler()
        Thread.setDefaultUncaughtExceptionHandler { thread, throwable ->
            e("CRASH", "FATAL EXCEPTION in thread ${thread.name}: ${throwable.message}", throwable)
            defaultHandler?.uncaughtException(thread, throwable)
        }
    }
}
